/**
 * This class has been generated by Fast Code Eclipse Plugin 
 * For more information please go to http://fast-code.sourceforge.net/
 * @author : Ad-Master
 * Created : 03/11/2015 06:01:50
 */

package pl.grm.geocompression;

import org.junit.*;
import static org.junit.Assert.*;
import pl.grm.geocompression.Math;



public class MathTest {

	
}
